# Generated by Django 5.2.3 on 2025-06-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='resume_file',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='summary',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='be_score',
            field=models.IntegerField(default=0, help_text='Backend score (0-100)'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='fe_score',
            field=models.IntegerField(default=0, help_text='Frontend score (0-100)'),
        ),
    ]
